@extends('homeController.servicio')

@section('contenidoServicio')

<div id="links">
    <a href="{{ asset('images/fem/01.jpg') }}" title="Foto 1" data-gallery><img src="{{ asset('images/thumbnails/fem/01 - Thumbnails.jpg') }}" alt=" " class="imagenServicio"><!-- completar alt --></a><a href="{{ asset('images/fem/02.jpg') }}" title="Foto 2" data-gallery><img src="{{ asset('images/thumbnails/fem/02 - Thumbnails.jpg') }}" alt=" " class="imagenServicio"></a><a href="{{ asset('images/fem/03.jpg') }}" title="Foto 3" data-gallery><img src="{{ asset('images/thumbnails/fem/03.jpg') }}" alt=" " class="imagenServicio"></a><a href="{{ asset('images/fem/04.jpg') }}" title="Foto 2" data-gallery><img src="{{ asset('images/thumbnails/fem/04 - Thumbnails.jpg') }}" alt=" " class="imagenServicio"></a><a href="{{ asset('images/fem/05.jpg') }}" title="Foto 3" data-gallery><img src="{{ asset('images/thumbnails/fem/05 - Thumbnails.jpg') }}" alt=" " class="imagenServicio"></a></a><a href="{{ asset('images/fem/06.jpg') }}" title="Foto 2" data-gallery><img src="{{ asset('images/thumbnails/fem/06.jpg') }}" alt=" " class="imagenServicio"></a><a href="{{ asset('images/fem/07.jpg') }}" title="Foto 2" data-gallery><img src="{{ asset('images/thumbnails/fem/07.jpg') }}" alt=" " class="imagenServicio"></a><a href="{{ asset('images/fem/08.jpg') }}" title="Foto 8" data-gallery><img src="{{ asset('images/thumbnails/fem/08.jpg') }}" alt=" " class="imagenServicio"></a>
</div>
<div>
    <h2>An&aacute;lisis por m&eacute;todo de elementos finitos</h2>
    <p class="parrafoServicios">El uso del m&eacute;todo de los elementos finitos es una potente herramienta utilizada en el an&aacute;lisis de componentes, sistemas y estructuras. Su utilizaci&oacute;n en la b&uacute;squeda de soluciones innovativas representa uno de los pilares de la ingenier&iacute;a moderna. Es por ello que FGM Ingenier&iacute;a cuenta con los medios para realizar una amplia gama de estudios y an&aacute;lisis, permitiendo obtener productos altamente optimizados, satisfaciendo las exigencias de nuestros clientes. Nuestros ingenieros realizan estudios anal&iacute;ticos y num&eacute;ricos de frecuencias naturales y modos de vibrar, an&aacute;lisis tensional, an&aacute;lisis de estructuras met&aacute;licas bajo cargas producidas por la acci&oacute;n del viento, an&aacute;lisis t&eacute;rmicos, estudios de sistemas bajo cargas contantes en el tiempo (creep), an&aacute;lisis de estabilidad en r&eacute;gimen el&aacute;stico y elastopl&aacute;stico, que conducen a la obtenci&oacute;n de memorias de c&aacute;lculo, curvas de energ&iacute;a, desplazamiento vs carga, reacciones de v&iacute;nculo, velocidad y aceleraci&oacute;n, esfuerzos caracter&iacute;sticos, etc.</p>
</div>

@endsection
